/*
389. Find the Difference
Easy
3.8K
423
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

https://leetcode.com/problems/find-the-difference/description/
*/

package main

import (
	"fmt"
)

func main() {

	s := "abcd"
	t := "abcde"

	fmt.Println(string(findTheDifference(s, t)))

}

func findTheDifference(s string, t string) byte {

	var asciiS byte
	var asciiT byte

	for i := 0; i < len(t); i++ {
		if i < len(s) {
			asciiS += s[i]
		}

		asciiT += t[i]
	}

	return asciiT - asciiS
}
